import type { Problem } from '../types';

export const problem: Problem = {
  id: 'find-the-difference',
  title: 'Find the Difference',
  difficulty: 'easy',
  tags: ['math'],
  description: `You are given two strings \`s\` and \`t\`.

String \`t\` is generated by randomly shuffling string \`s\` and then adding **one more letter** at a random position.

Return the letter that was added to \`t\`.`,
  constraints: [
    '`0 <= s.length <= 1000`',
    '`t.length == s.length + 1`',
    '`s` and `t` consist of lowercase English letters.',
  ],
  examples: [
    {
      input: 's = "abcd", t = "abcde"',
      output: '"e"',
      explanation: '"e" is the letter that was added.',
    },
    {
      input: 's = "", t = "y"',
      output: '"y"',
    },
  ],
  hints: [
    'XOR all characters in both strings together. Since all characters in `s` pair up with characters in `t`, the result is the extra character.',
  ],
  functionName: 'findTheDifference',
  params: ['s', 't'],
  starterCode: {
    javascript: `function findTheDifference(s, t) {

}`,
    python: `def findTheDifference(s, t):
    pass`,
  },
  visibleTests: [
    { args: ['abcd', 'abcde'], expected: 'e' },
    { args: ['', 'y'], expected: 'y' },
  ],
  hiddenTests: [
    { args: ['a', 'aa'], expected: 'a' },
    { args: ['ae', 'aea'], expected: 'a' },
    { args: ['xyz', 'xyzz'], expected: 'z' },
    { args: ['abcdefghij', 'jabcdefghim'], expected: 'm' },
  ],
};
