import type { Problem } from '../types';

export const problem: Problem = {
  id: 'find-the-difference',
  title: 'Find the Difference',
  difficulty: 'easy',
  tags: ['strings', 'hash-map'],
  description: `You are given two strings \`s\` and \`t\`. String \`t\` is generated by random shuffling string \`s\` and then adding one more letter at a random position. Return the letter that was added to \`t\`.`,
  constraints: [
    '`0 <= s.length <= 1000`',
    '`t.length == s.length + 1`',
    '`s` and `t` consist of lowercase English letters.',
  ],
  examples: [
    {
      input: 's = "abcd", t = "abcde"',
      output: '"e"',
    },
    {
      input: 's = "", t = "y"',
      output: '"y"',
    },
    {
      input: 's = "a", t = "aa"',
      output: '"a"',
    },
  ],
  hints: [
    'Use a frequency map: count occurrences in both strings and find the character with an extra count in t.',
    'Alternatively, XOR all characters in both strings. The result is the added character.',
    `\`\`\`js
function findTheDifference(s, t) {
  let xor = 0;
  for (const c of s) xor ^= c.charCodeAt(0);
  for (const c of t) xor ^= c.charCodeAt(0);
  return String.fromCharCode(xor);
}\`\`\``,
  ],
  functionName: 'findTheDifference',
  params: ['s', 't'],
  starterCode: {
    javascript: `function findTheDifference(s, t) {

}`,
    python: `def findTheDifference(s, t):
    pass`,
  },
  visibleTests: [
    { args: ['abcd', 'abcde'], expected: 'e' },
    { args: ['', 'y'], expected: 'y' },
    { args: ['a', 'aa'], expected: 'a' },
  ],
  hiddenTests: [
    { args: ['ae', 'aea'], expected: 'a' },
    { args: ['ae', 'eae'], expected: 'e' },
    { args: ['xyz', 'xyzt'], expected: 't' },
    { args: ['lrw', 'lwrr'], expected: 'r' },
    { args: ['z', 'zz'], expected: 'z' },
  ],
};
