/**
 * Curated problem list memberships. Each list maps to the problem IDs it
 * contains. During bank initialization, each Problem's `lists` field is
 * hydrated from this registry — no need to edit individual problem files.
 *
 * IDs that don't exist in the bank are silently skipped; the UI counts
 * reflect only problems actually present.
 */
import type { ProblemList } from '../../types';

/**
 * Mapping from each curated list to the problem IDs it contains.
 * Only IDs that exist in the bank will be matched at runtime.
 */
export const LIST_PROBLEM_IDS: Readonly<Record<ProblemList, readonly string[]>> = {
  'blind-75': [
    'two-sum',
    'contains-duplicate',
    'product-of-array-except-self',
    'max-subarray',
    'maximum-product-subarray',
    'find-minimum-in-rotated-sorted-array',
    'search-in-rotated-sorted-array',
    '3sum',
    'container-with-most-water',
    'sum-of-two-integers',
    'number-of-1-bits',
    'counting-bits',
    'missing-number',
    'reverse-bits',
    'climbing-stairs',
    'coin-change',
    'longest-increasing-subsequence',
    'longest-common-subsequence',
    'word-break',
    'combination-sum',
    'house-robber',
    'house-robber-ii',
    'decode-ways',
    'unique-paths',
    'jump-game',
    'clone-graph',
    'course-schedule',
    'pacific-atlantic-water-flow',
    'number-of-islands',
    'longest-consecutive-sequence',
    'alien-dictionary',
    'graph-valid-tree',
    'number-of-connected-components-in-an-undirected-graph',
    'insert-interval',
    'merge-intervals',
    'non-overlapping-intervals',
    'meeting-rooms',
    'meeting-rooms-ii',
    'reverse-linked-list',
    'linked-list-cycle',
    'merge-two-sorted-linked-lists',
    'merge-k-sorted-lists',
    'remove-nth-node-from-end-of-list',
    'reorder-list',
    'set-matrix-zeroes',
    'spiral-matrix',
    'rotate-image',
    'word-search',
    'longest-substring-without-repeating',
    'longest-repeating-character-replacement',
    'minimum-window-substring',
    'valid-anagram',
    'group-anagrams',
    'valid-parentheses',
    'encode-decode-strings',
    'maximum-depth-binary-tree',
    'same-tree',
    'invert-binary-tree',
    'binary-tree-maximum-path-sum',
    'binary-tree-level-order-traversal',
    'serialize-and-deserialize-binary-tree',
    'subtree-of-another-tree',
    'construct-binary-tree-from-preorder-and-inorder-traversal',
    'validate-binary-search-tree',
    'kth-smallest-element-in-a-bst',
    'lowest-common-ancestor-bst',
    'implement-trie-prefix-tree',
    'word-search-ii',
    'find-median-from-data-stream',
    'top-k-frequent-elements',
  ],

  'leetcode-75': [
    // Array / String
    'merge-strings-alternately',
    'greatest-common-divisor-of-strings',
    'kids-with-the-greatest-number-of-candies',
    'can-place-flowers',
    'reverse-vowels-of-a-string',
    'reverse-words-in-a-string',
    'product-of-array-except-self',
    'increasing-triplet-subsequence',
    'string-compression',
    // Two Pointers
    'move-zeroes',
    'is-subsequence',
    'container-with-most-water',
    'max-number-of-k-sum-pairs',
    // Sliding Window
    'maximum-number-of-vowels-in-a-substring-of-given-length',
    'max-consecutive-ones-iii',
    'longest-subarray-of-1s-after-deleting-one-element',
    // Prefix Sum
    'find-the-highest-altitude',
    'find-pivot-index',
    // Hash Map / Set
    'unique-number-of-occurrences',
    'determine-if-two-strings-are-close',
    'equal-row-and-column-pairs',
    // Stack
    'removing-stars-from-a-string',
    'asteroid-collision',
    'decode-string',
    // Queue
    'number-of-recent-calls',
    'dota2-senate',
    // Linked List
    'delete-the-middle-node-of-a-linked-list',
    'odd-even-linked-list',
    'reverse-linked-list',
    'maximum-twin-sum-of-a-linked-list',
    // Binary Tree - DFS
    'maximum-depth-binary-tree',
    'leaf-similar-trees',
    'count-good-nodes-in-binary-tree',
    'path-sum-iii',
    'longest-zigzag-path-in-binary-tree',
    'lowest-common-ancestor-of-a-binary-tree',
    // Binary Tree - BFS
    'binary-tree-level-order-traversal',
    // Binary Search Tree
    'delete-node-in-a-bst',
    // Graphs - DFS
    'keys-and-rooms',
    'number-of-provinces',
    'reorder-list',
    // Graphs - BFS
    'nearest-exit-from-entrance-in-maze',
    'rotting-oranges',
    // Heap / Priority Queue
    'kth-largest-element-in-an-array',
    'smallest-number-in-infinite-set',
    'total-cost-to-hire-k-workers',
    // Binary Search
    'guess-number-higher-or-lower',
    'successful-pairs-of-spells-and-potions',
    'find-peak-element',
    'koko-eating-bananas',
    // Backtracking
    'letter-combinations-of-a-phone-number',
    'combination-sum-iii',
    // DP - 1D
    'n-th-tribonacci-number',
    'min-cost-climbing-stairs',
    'house-robber',
    'domino-and-tromino-tiling',
    // DP - Multidimensional
    'unique-paths',
    'longest-common-subsequence',
    'best-time-to-buy-and-sell-stock-with-transaction-fee',
    'edit-distance',
    // Monotonic Stack
    'daily-temperatures',
    'online-stock-span',
    // Intervals
    'non-overlapping-intervals',
    // Bit Manipulation
    'counting-bits',
    'single-number',
    // Trie
    'implement-trie-prefix-tree',
  ],

  'top-interview-150': [
    // Array / String
    'merge-sorted-array',
    'remove-duplicates-from-sorted-array',
    'rotate-array',
    'product-of-array-except-self',
    'jump-game',
    'longest-common-prefix',
    'reverse-words-in-a-string',
    'zigzag-conversion',
    'roman-to-integer',
    'trapping-rain-water',
    // Two Pointers
    'valid-palindrome',
    'is-subsequence',
    'two-sum-ii',
    '3sum',
    'container-with-most-water',
    // Sliding Window
    'minimum-window-substring',
    'longest-substring-without-repeating',
    // Matrix
    'valid-sudoku',
    'spiral-matrix',
    'rotate-image',
    'set-matrix-zeroes',
    // Hashmap
    'two-sum',
    'group-anagrams',
    'valid-anagram',
    'contains-duplicate',
    'longest-consecutive-sequence',
    // Intervals
    'merge-intervals',
    'insert-interval',
    // Stack
    'valid-parentheses',
    'min-stack',
    'largest-rectangle-in-histogram',
    // Linked List
    'reverse-linked-list',
    'merge-two-sorted-linked-lists',
    'linked-list-cycle',
    'add-two-numbers',
    'remove-nth-node-from-end-of-list',
    'sort-list',
    'reorder-list',
    'palindrome-linked-list',
    'lru-cache',
    // Binary Tree
    'maximum-depth-binary-tree',
    'same-tree',
    'invert-binary-tree',
    'binary-tree-level-order-traversal',
    'binary-tree-maximum-path-sum',
    'construct-binary-tree-from-preorder-and-inorder-traversal',
    'validate-binary-search-tree',
    'kth-smallest-element-in-a-bst',
    'lowest-common-ancestor-of-a-binary-tree',
    'subtree-of-another-tree',
    'serialize-and-deserialize-binary-tree',
    // Graph
    'number-of-islands',
    'clone-graph',
    'course-schedule',
    'course-schedule-ii',
    // Backtracking
    'permutations',
    'subsets',
    'combination-sum',
    'word-search',
    'letter-combinations-of-a-phone-number',
    'generate-parentheses',
    // Binary Search
    'search-in-rotated-sorted-array',
    'find-minimum-in-rotated-sorted-array',
    'find-peak-element',
    'koko-eating-bananas',
    'find-median-from-data-stream',
    // DP
    'climbing-stairs',
    'house-robber',
    'coin-change',
    'word-break',
    'longest-increasing-subsequence',
    'longest-common-subsequence',
    'edit-distance',
    'decode-ways',
    'unique-paths',
    // Bit Manipulation
    'single-number',
    'number-of-1-bits',
    'counting-bits',
    'reverse-bits',
    'missing-number',
    'sum-of-two-integers',
    // Math
    'palindrome-number',
    // Heap
    'kth-largest-element-in-an-array',
    'top-k-frequent-elements',
    'merge-k-sorted-lists',
    // Trie
    'implement-trie-prefix-tree',
    'word-search-ii',
  ],

  'top-100-liked': [
    'two-sum',
    'add-two-numbers',
    '3sum',
    'longest-substring-without-repeating',
    'longest-palindromic-substring',
    'container-with-most-water',
    'valid-parentheses',
    'merge-two-sorted-linked-lists',
    'generate-parentheses',
    'merge-k-sorted-lists',
    'remove-nth-node-from-end-of-list',
    'trapping-rain-water',
    'permutations',
    'rotate-image',
    'group-anagrams',
    'max-subarray',
    'jump-game',
    'merge-intervals',
    'climbing-stairs',
    'sort-colors',
    'minimum-window-substring',
    'subsets',
    'word-search',
    'largest-rectangle-in-histogram',
    'binary-tree-level-order-traversal',
    'maximum-depth-binary-tree',
    'construct-binary-tree-from-preorder-and-inorder-traversal',
    'binary-tree-maximum-path-sum',
    'palindrome-linked-list',
    'lru-cache',
    'min-stack',
    'number-of-islands',
    'reverse-linked-list',
    'coin-change',
    'product-of-array-except-self',
    'top-k-frequent-elements',
    'decode-string',
    'daily-temperatures',
    'find-median-from-data-stream',
    'single-number',
    'word-break',
    'linked-list-cycle',
    'sort-list',
    'invert-binary-tree',
    'kth-largest-element-in-an-array',
    'validate-binary-search-tree',
    'same-tree',
    'longest-consecutive-sequence',
    'longest-increasing-subsequence',
    'longest-common-subsequence',
    'edit-distance',
    'serialize-and-deserialize-binary-tree',
    'missing-number',
    'move-zeroes',
    'find-peak-element',
    'kth-smallest-element-in-a-bst',
    'lowest-common-ancestor-of-a-binary-tree',
    'implement-trie-prefix-tree',
    'counting-bits',
    'house-robber',
    'rotate-array',
    'combination-sum',
    'letter-combinations-of-a-phone-number',
    'subtree-of-another-tree',
    'reorder-list',
    'spiral-matrix',
    'unique-paths',
    'set-matrix-zeroes',
    'course-schedule',
    'clone-graph',
    'search-in-rotated-sorted-array',
    'find-minimum-in-rotated-sorted-array',
    'pacific-atlantic-water-flow',
    'longest-repeating-character-replacement',
    'non-overlapping-intervals',
    'insert-interval',
    'container-with-most-water',
  ],

  'neetcode-150': [
    // Arrays & Hashing
    'contains-duplicate',
    'valid-anagram',
    'two-sum',
    'group-anagrams',
    'top-k-frequent-elements',
    'product-of-array-except-self',
    'encode-decode-strings',
    'longest-consecutive-sequence',
    // Two Pointers
    'valid-palindrome',
    'two-sum-ii',
    '3sum',
    'container-with-most-water',
    'trapping-rain-water',
    // Sliding Window
    'longest-substring-without-repeating',
    'longest-repeating-character-replacement',
    'minimum-window-substring',
    // Stack
    'valid-parentheses',
    'min-stack',
    'generate-parentheses',
    'daily-temperatures',
    'largest-rectangle-in-histogram',
    // Binary Search
    'binary-search',
    'search-in-rotated-sorted-array',
    'find-minimum-in-rotated-sorted-array',
    'koko-eating-bananas',
    'find-median-from-data-stream',
    // Linked List
    'reverse-linked-list',
    'merge-two-sorted-linked-lists',
    'reorder-list',
    'remove-nth-node-from-end-of-list',
    'linked-list-cycle',
    'merge-k-sorted-lists',
    'add-two-numbers',
    'lru-cache',
    // Trees
    'invert-binary-tree',
    'maximum-depth-binary-tree',
    'same-tree',
    'subtree-of-another-tree',
    'lowest-common-ancestor-of-a-binary-tree',
    'binary-tree-level-order-traversal',
    'validate-binary-search-tree',
    'kth-smallest-element-in-a-bst',
    'construct-binary-tree-from-preorder-and-inorder-traversal',
    'binary-tree-maximum-path-sum',
    'serialize-and-deserialize-binary-tree',
    // Tries
    'implement-trie-prefix-tree',
    'word-search-ii',
    // Heap
    'kth-largest-element-in-an-array',
    'top-k-frequent-elements',
    // Backtracking
    'subsets',
    'combination-sum',
    'permutations',
    'subsets-ii',
    'combination-sum-ii',
    'word-search',
    'palindrome-partitioning',
    'letter-combinations-of-a-phone-number',
    // Graphs
    'number-of-islands',
    'clone-graph',
    'pacific-atlantic-water-flow',
    'course-schedule',
    'course-schedule-ii',
    'graph-valid-tree',
    'number-of-connected-components-in-an-undirected-graph',
    'rotting-oranges',
    // DP
    'climbing-stairs',
    'min-cost-climbing-stairs',
    'house-robber',
    'house-robber-ii',
    'longest-palindromic-substring',
    'decode-ways',
    'coin-change',
    'maximum-product-subarray',
    'word-break',
    'longest-increasing-subsequence',
    'unique-paths',
    'longest-common-subsequence',
    'jump-game',
    'edit-distance',
    // Greedy
    'max-subarray',
    'jump-game-ii',
    // Intervals
    'insert-interval',
    'merge-intervals',
    'non-overlapping-intervals',
    'meeting-rooms',
    'meeting-rooms-ii',
    // Math & Geometry
    'rotate-image',
    'spiral-matrix',
    'set-matrix-zeroes',
    // Bit Manipulation
    'single-number',
    'number-of-1-bits',
    'counting-bits',
    'reverse-bits',
    'missing-number',
    'sum-of-two-integers',
  ],

  'neetcode-250': [
    // Everything in neetcode-150, plus extras
    // Arrays & Hashing
    'contains-duplicate',
    'valid-anagram',
    'two-sum',
    'group-anagrams',
    'top-k-frequent-elements',
    'product-of-array-except-self',
    'encode-decode-strings',
    'longest-consecutive-sequence',
    'sort-colors',
    'next-permutation',
    // Two Pointers
    'valid-palindrome',
    'two-sum-ii',
    '3sum',
    'container-with-most-water',
    'trapping-rain-water',
    // Sliding Window
    'longest-substring-without-repeating',
    'longest-repeating-character-replacement',
    'minimum-window-substring',
    'max-consecutive-ones-iii',
    // Stack
    'valid-parentheses',
    'min-stack',
    'generate-parentheses',
    'daily-temperatures',
    'online-stock-span',
    'largest-rectangle-in-histogram',
    'asteroid-collision',
    'decode-string',
    // Binary Search
    'binary-search',
    'search-in-rotated-sorted-array',
    'find-minimum-in-rotated-sorted-array',
    'koko-eating-bananas',
    'find-peak-element',
    'find-median-from-data-stream',
    // Linked List
    'reverse-linked-list',
    'merge-two-sorted-linked-lists',
    'reorder-list',
    'remove-nth-node-from-end-of-list',
    'linked-list-cycle',
    'merge-k-sorted-lists',
    'add-two-numbers',
    'palindrome-linked-list',
    'sort-list',
    'odd-even-linked-list',
    'lru-cache',
    // Trees
    'invert-binary-tree',
    'maximum-depth-binary-tree',
    'same-tree',
    'subtree-of-another-tree',
    'lowest-common-ancestor-of-a-binary-tree',
    'binary-tree-level-order-traversal',
    'validate-binary-search-tree',
    'kth-smallest-element-in-a-bst',
    'construct-binary-tree-from-preorder-and-inorder-traversal',
    'binary-tree-maximum-path-sum',
    'serialize-and-deserialize-binary-tree',
    'count-good-nodes-in-binary-tree',
    'path-sum-iii',
    'delete-node-in-a-bst',
    // Tries
    'implement-trie-prefix-tree',
    'word-search-ii',
    // Heap
    'kth-largest-element-in-an-array',
    'top-k-frequent-elements',
    'smallest-number-in-infinite-set',
    'total-cost-to-hire-k-workers',
    // Backtracking
    'subsets',
    'combination-sum',
    'permutations',
    'subsets-ii',
    'combination-sum-ii',
    'word-search',
    'palindrome-partitioning',
    'letter-combinations-of-a-phone-number',
    'generate-parentheses',
    'sudoku-solver',
    'combination-sum-iii',
    // Graphs
    'number-of-islands',
    'clone-graph',
    'pacific-atlantic-water-flow',
    'course-schedule',
    'course-schedule-ii',
    'graph-valid-tree',
    'number-of-connected-components-in-an-undirected-graph',
    'rotting-oranges',
    'number-of-provinces',
    'keys-and-rooms',
    'nearest-exit-from-entrance-in-maze',
    'alien-dictionary',
    // DP
    'climbing-stairs',
    'min-cost-climbing-stairs',
    'house-robber',
    'house-robber-ii',
    'longest-palindromic-substring',
    'decode-ways',
    'coin-change',
    'maximum-product-subarray',
    'word-break',
    'longest-increasing-subsequence',
    'unique-paths',
    'longest-common-subsequence',
    'jump-game',
    'edit-distance',
    'n-th-tribonacci-number',
    'domino-and-tromino-tiling',
    'best-time-to-buy-and-sell-stock-with-transaction-fee',
    // Greedy
    'max-subarray',
    'jump-game-ii',
    // Intervals
    'insert-interval',
    'merge-intervals',
    'non-overlapping-intervals',
    'meeting-rooms',
    'meeting-rooms-ii',
    // Math & Geometry
    'rotate-image',
    'spiral-matrix',
    'set-matrix-zeroes',
    'palindrome-number',
    // Bit Manipulation
    'single-number',
    'number-of-1-bits',
    'counting-bits',
    'reverse-bits',
    'missing-number',
    'sum-of-two-integers',
    // Monotonic Stack
    'daily-temperatures',
    'online-stock-span',
    'largest-rectangle-in-histogram',
  ],

};
