import type { Problem } from '../types';

export const problem: Problem = {
  id: 'minimum-size-subarray-in-infinite-array',
  title: 'Minimum Size Subarray in Infinite Array',
  difficulty: 'medium',
  tags: ['sliding-window', 'arrays'],
  description: `You are given a **0-indexed** array \`nums\` and an integer \`target\`.

A **0-indexed** array \`infinite_nums\` is generated by infinitely appending the elements of \`nums\` to itself.

Return the **length of the shortest subarray** of \`infinite_nums\` with a sum equal to \`target\`. If there is no such subarray, return \`-1\`.

**Args:** \`nums: number[], target: number\`

**Example 1:**

\`\`\`
Input: nums = [1,2,3], target = 5
Output: 2
Explanation: The subarray [2,3] has length 2 and sum 5.
\`\`\`

**Example 2:**

\`\`\`
Input: nums = [1,1,1,2,3], target = 7
Output: 4
Explanation: The subarray [1,1,2,3] (indices 1–4) has sum 7 and length 4.
\`\`\`

**Example 3:**

\`\`\`
Input: nums = [2,4,6,8], target = 3
Output: -1
\`\`\``,
  constraints: [
    '1 <= nums.length <= 10^5',
    '1 <= nums[i] <= 10^5',
    '1 <= target <= 10^9',
  ],
  examples: [
    { input: 'nums = [1,2,3], target = 5', output: '2' },
    { input: 'nums = [1,1,1,2,3], target = 7', output: '4' },
    { input: 'nums = [2,4,6,8], target = 3', output: '-1' },
  ],
  hints: [
    'Let `total` = sum of `nums`. The answer uses `fullLoops = Math.floor(target / total)` full copies. The remainder `rem = target % total` must be covered by a contiguous subarray of length at most `2*n`.',
    'To find the shortest subarray with sum `rem` in a double copy of `nums`, use a two-pointer / sliding window on `nums` concatenated with itself.',
    'If `rem === 0`, the answer is `fullLoops * n`. Otherwise, find the shortest subarray of sum `rem` in the double array, add `fullLoops * n` to its length.',
  ],
  functionName: 'minSizeSubarray',
  params: ['nums', 'target'],
  starterCode: {
    javascript: 'function minSizeSubarray(nums, target) {\n  \n}\n',
    python: 'def minSizeSubarray(nums, target):\n    ',
    typescript: 'function minSizeSubarray(nums: number[], target: number): number {\n  \n}\n',
  },
  visibleTests: [
    { args: [[1, 2, 3], 5], expected: 2 },
    { args: [[1, 1, 1, 2, 3], 7], expected: 4 },
    { args: [[2, 4, 6, 8], 3], expected: -1 },
  ],
  hiddenTests: [
    { args: [[1], 3], expected: 3 },
    { args: [[2], 6], expected: 3 },
    { args: [[1, 2], 4], expected: 3 },
    { args: [[1, 2, 3], 9], expected: 4 },
    { args: [[1, 2, 3], 6], expected: 3 },
    { args: [[3], 7], expected: -1 },
  ],
};
